@Basket_HostAddress = https://localhost:7244/basket

### Get shopping cart for user
GET {{Basket_HostAddress}}/denys
Accept: application/json

### Create or update shopping cart
POST {{Basket_HostAddress}}/
Content-Type: application/json

{
  "UserName": "denys",
  "Items": [
    {
      "Quantity": 2,
      "Color": "Red",
      "Price": 0,
      "ProductId": 1,
      "ProductName": "Solar Powered Flashlight"
    },
    {
      "Quantity": 1,
      "Color": "Blue",
      "Price": 0,
      "ProductId": 2,
      "ProductName": "Hiking Poles"
    }
  ]
}

### Delete shopping cart for user
DELETE {{Basket_HostAddress}}/denys
Accept: application/json
